[package]
name = "prtgn"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
tui-textarea = "0.7.0"
clap = { version = "4", features = ["derive"] }
anyhow = "1.0.100"
