name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
        # Optional: Define inputs if you want to pass custom parameters
        inputs:
          logLevel:
            description: 'Log level'
            required: true
            default: 'info'
            type: choice
            options:
            - info
            - warning
            - debug

jobs:
  get-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get the version from Cargo.toml
        id: get_version
        run: echo "VERSION=$(grep '^version' Cargo.toml | head -n 1 | cut -d '"' -f 2)" >> $GITHUB_OUTPUT

  windows-release:
    runs-on: windows-latest
    needs: get-version
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        target: x86_64-pc-windows-gnu

    - name: Build for Windows
      run: cargo build --release --target x86_64-pc-windows-gnu

    - name: Create Windows Installer
      env:
        APP_VERSION: ${{ needs.get-version.outputs.version }}
      run: |
        choco install innosetup
        iscc /DGITHUB_ACTIONS inno.iss

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prtgn-windows-installer
        path: Output/prtgn_v${{ needs.get-version.outputs.version }}_x86_64.exe

  debian-release:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install cargo-deb
      run: cargo install cargo-deb

    - name: Build for Debian
      run: cargo deb --output target/debian/prtgn_v${{ needs.get-version.outputs.version }}_amd64.deb

    - name: Upload Debian Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prtgn-debian-package
        path: target/debian/prtgn_v${{ needs.get-version.outputs.version }}_amd64.deb

  fedora-release:
    runs-on: ubuntu-latest
    needs: get-version
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install cargo-rpm
      run: cargo install cargo-rpm

    - name: Build for Fedora (RPM)
      run: cargo rpm build

    - name: Upload Fedora Artifact
      uses: actions/upload-artifact@v4
      with:
        name: prtgn-fedora-package
        path: target/release/rpmbuild/RPMS/*/*.rpm

  create-release:
    runs-on: ubuntu-latest
    needs: [get-version, windows-release, debian-release, fedora-release]
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Windows Installer
      uses: actions/download-artifact@v4
      with:
        name: prtgn-windows-installer
        path: prtgn-windows-installer

    - name: Download Debian Package
      uses: actions/download-artifact@v4
      with:
        name: prtgn-debian-package
        path: prtgn-debian-package

    - name: Download Fedora Package
      uses: actions/download-artifact@v4
      with:
        name: prtgn-fedora-package
        path: prtgn-fedora-package

    - name: Generate release notes
      run: sed 's/<version>/${{ needs.get-version.outputs.version }}/g' RELEASE_TEMPLATE > release_notes.md

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ needs.get-version.outputs.version }}
        name: Release v${{ needs.get-version.outputs.version }}
        body_path: release_notes.md
        draft: true
        prerelease: false
        files: |
          prtgn-windows-installer/*.exe
          prtgn-debian-package/*.deb
          prtgn-fedora-package/**/*.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}